version: "3.7"

services:
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - 80:80/tcp
    volumes:
      - ./config/nginx/conf.d/http.conf:/etc/nginx/conf.d/default.conf
    links:
      - mailarchiva

  mailarchiva:
    expose:
      - "8080"
