version: "3.7"

services:
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./config/nginx/conf.d/https.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/nginx_tls.crt:/run/secrets/nginx_tls_crt:ro
      - ./config/nginx/nginx_tls.key:/run/secrets/nginx_tls_key:ro
      - ./config/nginx/dhparam.pem:/run/secrets/nginx_dhparam:ro
    links:
      - mailarchiva

  mailarchiva:
    expose:
      - "8080"